# Generated by Django 5.0.4 on 2024-04-27 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
