# Generated by Django 5.0.4 on 2024-05-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_alter_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
    ]
